module Domain.Move.BuiltIn where

data BuiltInMove =
  AcidArmor
  | LeechSeed
  | LightScreen
  | PainSplit
  | QuiverDance
  | Protect
  | RainDance
  | Reflect
  | Rest
  | Sandstorm
  | SleepPowder
  | SleepTalk
  | SwordsDance
  | Toxic
  | WillOWisp
  | Yawn
  | MetalBurst
  | SheerCold
  | Struggle
  | Acrobatics
  | AirSlash
  | AquaJet
  | AuraSphere
  | Avalanche
  | Blizzard
  | BodySlam
  | BraveBird
  | BugBuzz
  | BulletPunch
  | BrickBreak
  | CloseCombat
  | Crunch
  | DarkPulse
  | DracoMeteor
  | DragonClaw
  | DragonPulse
  | EarthPower
  | Earthquake
  | EnergyBall
  | ExtremeSpeed
  | FakeOut
  | FireBlast
  | FirePunch
  | Flamethrower
  | FlareBlitz
  | FlashCannon
  | FocusBlast
  | GigaDrain
  | GrassKnot
  | HammerArm
  | HeadSmash
  | HeatWave
  | HydroPump
  | IceBeam
  | IceFang
  | IcePunch
  | IceShard
  | IcyWind
  | IronTail
  | LeafStorm
  | MachPunch
  | MuddyWater
  | Outrage
  | Payback
  | Psychic
  | QuickAttack
  | RockBlast
  | RockSlide
  | Scald
  | SeedBomb
  | ShadowBall
  | SignalBeam
  | SludgeBomb
  | SolarBeam
  | StoneEdge
  | SuckerPunch
  | Superpower
  | Surf
  | Thunderbolt
  | UTurn
  | VoltTackle
  | Waterfall
  | WaterPulse
  | WaterSpout
  | WildCharge
  | WoodHammer
  | XScissor
  | ZenHeadbutt
  deriving (Eq,Show,Read,Ord,Enum)
